### ISSUE TITLE
How to re-generate example client?

### ISSUE THREAD

**Issue by warmans** [flowup/api-client-generator#19]
Is the swagger file missing to regenerate the example code (example dir in project)? Additionally it seems like this target is not functional in the package.json: 

```
    "gen": "ts-node ./src/main.ts",
```

I guess it should be `...main.ts -s the-missing-swagger-file.json -o example`.

**Comment by vmasek** [comment]
We will add tests for the generator in near future. The biggest priority is to generate module with support for namespaced (micro)services.

**Comment by warmans** [comment]
This is no longer relevant.
