### ISSUE TITLE
[api-client] array params methods should use append instead of set

### ISSUE THREAD

**Issue by warmans** [flowup/api-client-generator#31]
here is an example swagger parameter definition: 
```
{
  "type": "array",
  "items": {
    "type": "string"
  },
  "name": "filters",
  "in": "query"
}
```

and here is what gets generated for that parameter

```
  listThings(filters: string[], options?: HttpOptions): Observable<models.V2RuleList> {
    const path = `/api/v2/things`;
    options = {...this.options, ...options};

    if (filters) {
      options.params = options.params.set('filters', String(filters));
    }
    return this.sendRequest<models.V2ThingList>('GET', path, options);
  }
```

The filters array ends up being joined with commas. 

__What should happen:__

The generated code for the param should look more like this: 

```
    if (filters) {
      filters.forEach(v => {
        options.params = options.params.append('filters', v);
      });
    }
```

This is unfortunately arguable since [apparently](https://stackoverflow.com/questions/24059773/correct-way-to-pass-multiple-values-for-same-parameter-name-in-get-request) there is not a clear standard. However multiple params with the same name is the most and reliable approach AFAIK so it should probably be used.

The functionality could be hidden behind a flag for backwards compatibility i.e. it uses `set` by default but `append` if `--append-array-params` is supplied during generation.

**Comment by vmasek** [comment]
I think the best will be to have the option that will switch the `set` for `append` as you proposed

**Comment by warmans** [comment]
OK I'll probably work on a PR for this later today.

**Comment by vmasek** [comment]
In beta branch I have refactored the code and split it to separate functions, I am also planning to add linting. You can wait till it is in master so I wouldn't mess up your work with conflicts.
