### ISSUE TITLE
BASIC_TS_TYPE_REGEX  

### ISSUE THREAD

**Issue by adamzoltan873** [flowup/api-client-generator#44]
Hi flowup,

In my swagger file I have a type, which contains the letters 'any' in it. Your pattern matches this type against BASIC_TS_TYPE_REGEX. Here is the word: Tanulmany
See below my fix for this. 
Regards, adamzoltan

old
`const BASIC_TS_TYPE_REGEX = /^string|number|integer|boolean|null|undefined|any|Object|Date|File|Blob$/;
`
new
`const BASIC_TS_TYPE_REGEX = /\b(string|number|integer|boolean|null|undefined|any|Object|Date|File|Blob)\b/;
`

**Comment by vmasek** [comment]
Thanks for a report :+1: we will add this to test cases and fix in next minor release
