### ISSUE TITLE
Escape keys with non-word characters or ones starting with a number

### ISSUE THREAD

**Issue by Dasio** [flowup/api-client-generator#54]
When field's name starts with a number it should be quoted
Eg:
```
interface Sample {
  name: string;
  '42wololo': string;
}
```
Instead of (current wrong behavior):
```
interface Sample {
  name: string;
  42wololo: string;
}
```

**Comment by vmasek** [comment]
We need to escape all interface keys that are either starting with a number (`42wololo`) and also ones that contain non-word characters like `+1`, `some-key` or `yet@notherKey`
