### ISSUE TITLE
Multiple swagger files: Project structure

### ISSUE THREAD

**Issue by stephenwil** [flowup/api-client-generator#73]
If I've microservices each represented by a swagger file, how do you perceive the host project to structure the multiple generated clients?

e.g. If I have all my generated clients in ./src/app/api/generatedA, ./src/app/api/generatedB, etc
Then I'll have multiple APIClient & APIClientInterface classes.
I'd have to add in namespaces to avoid name collisions etc.

**Comment by stephenwil** [comment]
Thinking about it a bit more, if I can perhaps use a feature module to consume each generated client, and import APIClient as xAPIClient etc

**Comment by vmasek** [comment]
I am not sure about how to answer but I can tell you how we use it with microservices.

We have one swagger file for every microservice which we merge together via some tool. 

This one merged swagger file now has `tag` for each of the service. When generating the client(s) we use the flag `-t/--splitPathTags` so the services are separated by their tags.

You can see the example in one of the test [reference files](https://github.com/flowup/api-client-generator/tree/master/tests/github/api) 

Service clients are each in separate folder and all of the models are in one folder. There is a possibility for model name collisions, but thats something we would notice earlier, when merging the swaggers.

**Comment by vmasek** [comment]
@stephenwil does this satisfies your need? Or should we collaborate more on the solution?
