### ISSUE TITLE
Regression for required fields

### ISSUE THREAD

**Issue by Azuka** [flowup/api-client-generator#76]
Hi. The recent update in #75 seems to have broken the generation. Even with required attributes set, all models are generated with all fields optional. Do you mind taking a look?

**Comment by vmasek** [comment]
Hi @Azuka, can you please share the model definition? Does that happen in method parameter or response?

If it is response it has to be marked differently than the parameter for required property.
See the example of `ItemList` in tests ([model](https://github.com/flowup/api-client-generator/blob/master/tests/custom/api/models/item-list.model.ts#L10) and [definiton](https://github.com/flowup/api-client-generator/blob/master/tests/custom/swagger.yaml#L110))

Or example for method `getItems` params where they are both required ([method params](https://github.com/flowup/api-client-generator/blob/master/tests/custom/api/api-client.service.ts#L46...L47) and [method definition](https://github.com/flowup/api-client-generator/blob/master/tests/custom/swagger.yaml#L17))

**Comment by Azuka** [comment]
Thanks @vmasek for your very prompt response, and sorry for my late one. I looked at the definitions and realized none of the models were marked required.

I'll stick to 4.1.0 for now.
