### ISSUE TITLE
Support responseType in HttpOptions

### ISSUE THREAD

**Issue by MuraliNunna** [flowup/api-client-generator#77]
Hi,

For endpoints serving file downloads, HttpOptions need to support **responseType**. The current generated code doesn't support this.

I dug around the issues, and found that it was actually removed here at https://github.com/flowup/api-client-generator/commit/74c53a4570b8fba0dcd1f83957b35fd53ffb3c46

I had to manually change the generated code to

```js
export interface HttpOptions {
  headers?: HttpHeaders;
  params?: HttpParams;
  reportProgress?: boolean;
  withCredentials?: boolean;
  responseType?: any;
}
```
to support the endpoint

Any ideas?

**Comment by vmasek** [comment]
Thanks for a report, it was removed due to some issues we had with that, I'll have a look at it during the week.

Is it only `responseType` that you need? Does adding it into `HttpOptions` solve your problem?

**Comment by MuraliNunna** [comment]
Yes, adding the responseType to HttpOptions solves the issue.
