### ISSUE TITLE
APIs with form 'consumes' don't generate valid client code, suggesting an optional filter

### ISSUE THREAD

**Issue by jalmeida-mct** [flowup/api-client-generator#78]
Currently generator works fine except when an API accepts form data, for example for a file upload. The generated code causes a compile error due to a bad template.

I checked the issues and looks like there's a rewrite in the works, so I added an optional command line argument to skip generating those particular methods instead, which is 100% backwards compatible. Please check my PR

**Comment by vmasek** [comment]
@jalmeida-mct could you please check the functionality on the latest version ([4.3.0](https://github.com/flowup/api-client-generator/releases/tag/4.3.0)). I've added support for multipart form data so this should be resolved by it. 

We'd rather have it working and let excluding it as a secondary option if it doesn't work.

Please have a look and report if your problem got resolved so we can close this or work on it further

**Comment by jalmeida-mct** [comment]
awesome! I'll test it and let you know

**Comment by jalmeida-mct** [comment]
Looks like the generated code is correct!

Had to do a bit of type juggling. Getting a few of these:
```
The 'Object' type is assignable to very few other types. Did you mean to use the 'any' type instead?
```
Which is an easy fix with a cast to <any>. I'm doing that and moving on. Thanks for the fix!
