### ISSUE TITLE
Incompatible with Angular 10

### ISSUE THREAD

**Issue by Azuka** [flowup/api-client-generator#93]
The api client module generated needs a small fix in the template to support Angular 10, ie a change from

```typescript
  static forRoot(config: APIClientModuleConfig = {}): ModuleWithProviders {
```

to 

```typescript
  static forRoot(config: APIClientModuleConfig = {}): ModuleWithProviders<APIClientModule> {
```

I'm opening a PR shortly to fix that.

**Comment by vmasek** [comment]
Thank you very much for the issue and PR 👍 
I'll try to release a new version during the week.
