### ISSUE TITLE
Is it possible to fetch file from remote and then generate

### ISSUE THREAD

**Issue by BioPhoton** [flowup/api-client-generator#99]
Is is possible that the generate command resolves files over HTTP?

**Comment by vmasek** [comment]
Currently, the easiest way to do so is to use for example `curl` and chain the commands.

`curl https://raw.githubusercontent.com/flowup/api-client-generator/master/tests/custom/swagger.yaml -o swagger.yaml &&npm run generate -- -s swagger.yaml -o ./output`

This will download and save the `swagger.yaml` and use the file to generate API client. What would be a nice improvement is an ability to feed the swagger file via stdin so we don't have to save it, this can be added in next release (I'll add it to backlog).
